---
abstract: 'an HTTP URI field'
author:
  - 'Roman F. <romanf@cpan.org>'
build_requires:
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormHandlerX-Field-URI-HTTP
requires:
  HTML::FormHandler::Field::Text: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Regexp::Common: 0
  URI: 0
  namespace::autoclean: 0
  version: 0
resources:
  repository: git://github.com/moltar/HTML-FormHandlerX-Field-URI-HTTP.git
version: v0.2
